api:
  version: /api/v1

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/todolist?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
    username: root
    password: mariadb

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        batch_fetch_style: dynamic
    open-in-view: false # true

decorator:
  datasource:
    p6spy:
      enable-logging: true

server:
  error:
    include-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel:
      enabled: true

redis:
  host: 127.0.0.1
  port: 6379

jwt:
  bearer_type: Bearer
  authorization_header: Authorization
  authorities_key: auth
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access_token_expire_time: 5 # minute
  refresh_token_expire_time: 30 # minute

springdoc:
  version: '0.0.1'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: method # alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - ${api.version}/**